name: qr_scanner
description: QR Scanner

publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  custom_navigation_bar: ^0.6.0
  firebase_core: 
  firebase_admob: ^0.10.3
  firebase_analytics: 
  firebase_crashlytics: 
  flutter_icons: ^1.1.0
  fluttercontactpicker: ^4.2.1
  gallery_saver: ^2.0.1
  google_fonts: ^1.1.1
  image_editor: ^0.7.3
  image_gallery_saver: ^1.6.7
  image_picker: ^0.6.7+4
  path: ^1.7.0
  permission_handler: ^5.0.1+1
  photo_view: ^0.9.2
  qrscan: ^0.2.21
  share: ^0.6.5+4
  splashscreen: ^1.3.5
  sqflite: ^1.3.2+1
  url_launcher: ^5.7.10
  wc_flutter_share: ^0.2.2
  extended_image: ^1.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.8.0






flutter_icons:
  android: true
  ios: true
  image_path: "assets/17.png"

flutter:

  uses-material-design: true

  assets:
    - assets/
